// toggleClass,addClass,removeClassのCを大文字ではなく小文字にしてしまうと動作しないので注意すること！！！！！！！！！！！！！！
// english
$("#button-english-1").on("click",function(){
    $(".figma").not("#english-boxes-1").addClass("hidden")
    $("#english-boxes-1").removeClass("hidden")
});
$("#button-english-2").on("click",function(){
    $(".figma").not("#english-boxes-2").addClass("hidden")
    $("#english-boxes-2").removeClass("hidden")
});
$("#button-english-3").on("click",function(){
    $(".figma").not("#english-boxes-3").addClass("hidden")
    $("#english-boxes-3").removeClass("hidden")
});
$("#button-english-4").on("click",function(){
    $(".figma").not("#english-boxes-4").addClass("hidden")
    $("#english-boxes-4").removeClass("hidden")
});
$("#button-english-5").on("click",function(){
    $(".figma").not("#english-boxes-5").addClass("hidden")
    $("#english-boxes-5").removeClass("hidden")
});
$("#button-english-6").on("click",function(){
    $(".figma").not("#english-boxes-6").addClass("hidden")
    $("#english-boxes-6").removeClass("hidden")
});
// japanese
$("#button-japanese-1").on("click",function(){
    $(".figma").not("#japanese-boxes-1").addClass("hidden")
    $("#japanese-boxes-1").removeClass("hidden")
});
$("#button-japanese-2").on("click",function(){
    $(".figma").not("#japanese-boxes-2").addClass("hidden")
    $("#japanese-boxes-2").removeClass("hidden")
});
$("#button-japanese-3").on("click",function(){
    $(".figma").not("#japanese-boxes-3").addClass("hidden")
    $("#japanese-boxes-3").removeClass("hidden")
});
$("#button-japanese-4").on("click",function(){
    $(".figma").not("#japanese-boxes-4").addClass("hidden")
    $("#japanese-boxes-4").removeClass("hidden")
});
$("#button-japanese-5").on("click",function(){
    $(".figma").not("#japanese-boxes-5").addClass("hidden")
    $("#japanese-boxes-5").removeClass("hidden")
});
$("#button-japanese-6").on("click",function(){
    $(".figma").not("#japanese-boxes-6").addClass("hidden")
    $("#japanese-boxes-6").removeClass("hidden")
});
// math
$("#button-math-1").on("click",function(){
    $(".figma").not("#math-boxes-1").addClass("hidden")
    $("#math-boxes-1").removeClass("hidden")
});
$("#button-math-2").on("click",function(){
    $(".figma").not("#math-boxes-2").addClass("hidden")
    $("#math-boxes-2").removeClass("hidden")
});
$("#button-math-3").on("click",function(){
    $(".figma").not("#math-boxes-3").addClass("hidden")
    $("#math-boxes-3").removeClass("hidden")
});
$("#button-math-4").on("click",function(){
    $(".figma").not("#math-boxes-4").addClass("hidden")
    $("#math-boxes-4").removeClass("hidden")
});
$("#button-math-5").on("click",function(){
    $(".figma").not("#math-boxes-5").addClass("hidden")
    $("#math-boxes-5").removeClass("hidden")
});
$("#button-math-6").on("click",function(){
    $(".figma").not("#math-boxes-6").addClass("hidden")
    $("#math-boxes-6").removeClass("hidden")
});
// science
$("#button-science-1").on("click",function(){
    $(".figma").not("#science-boxes-1").addClass("hidden")
    $("#science-boxes-1").removeClass("hidden")
});
$("#button-science-2").on("click",function(){
    $(".figma").not("#science-boxes-2").addClass("hidden")
    $("#science-boxes-2").removeClass("hidden")
});
$("#button-science-3").on("click",function(){
    $(".figma").not("#science-boxes-3").addClass("hidden")
    $("#science-boxes-3").removeClass("hidden")
});
$("#button-science-4").on("click",function(){
    $(".figma").not("#science-boxes-4").addClass("hidden")
    $("#science-boxes-4").removeClass("hidden")
});
$("#button-science-5").on("click",function(){
    $(".figma").not("#science-boxes-5").addClass("hidden")
    $("#science-boxes-5").removeClass("hidden")
});
$("#button-science-6").on("click",function(){
    $(".figma").not("#science-boxes-6").addClass("hidden")
    $("#science-boxes-6").removeClass("hidden")
});
// society
$("#button-society-1").on("click",function(){
    $(".figma").not("#society-boxes-1").addClass("hidden")
    $("#society-boxes-1").removeClass("hidden")
});
$("#button-society-2").on("click",function(){
    $(".figma").not("#society-boxes-2").addClass("hidden")
    $("#society-boxes-2").removeClass("hidden")
});
$("#button-society-3").on("click",function(){
    $(".figma").not("#society-boxes-3").addClass("hidden")
    $("#society-boxes-3").removeClass("hidden")
});
$("#button-society-4").on("click",function(){
    $(".figma").not("#society-boxes-4").addClass("hidden")
    $("#society-boxes-4").removeClass("hidden")
});
$("#button-society-5").on("click",function(){
    $(".figma").not("#society-boxes-5").addClass("hidden")
    $("#society-boxes-5").removeClass("hidden")
});
$("#button-society-6").on("click",function(){
    $(".figma").not("#society-boxes-6").addClass("hidden")
    $("#society-boxes-6").removeClass("hidden")
});
